
networks:
  default: mainnet-fork
  mainnet-fork:
    explorer: https://api.etherscan.io/api
    cmd: ganache-cli
    cmd_settings:
      accounts: 10
      mnemonic: brownie
      fork: https://eth-mainnet.alchemyapi.io/v2/$ALCHEMYAPI_TOKEN
      default_balance: 500 ether
      chain_id: 1

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1

autofetch_sources: true

compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.1"